### ISSUE TITLE
grafana_admin_password is mandatory

### ISSUE THREAD

**Issue by ghost** [ansiblebit/grafana#3]
In my opinion that would be better to preserve the official default `grafana_admin_password` (Cf. http://docs.grafana.org/installation/configuration/#admin-password).

But, if you do not want to set the `grafana_admin_password` in the defaults, I suggest to change the readme :

```md
## Playbooks

    - hosts: servers
      roles:
         - role: ansiblebit.grafana
           grafana_admin_password: 'P4ssw0rd'
```

**Comment by steenzout** [comment]
thank you for your feedback.

added this to https://github.com/ansiblebit/grafana/releases/tag/2.14.2 .
